Fix issue with escape characters in strings
sophof/blaise pull request #11
Opened 2023-11-29 15:50 UTC by reijeridema

Also improves read_fwf tests for DATETYPE to be independent of locale.

2023-11-30 10:42 UTC, sophof requested changes
Bedankt, super mooi dat het maar een kleine aanpassing nodig had uiteindelijk. Heb nog wat kleine opmerkingen wel.

2023-11-30 10:42 UTC, sophof commented on tests/testthat/test_write_fwf_blaise.R
> +  blafile = tempfile(fileext = '.asc')
Beter om de extensie van de blafile hier .bla te maken. maakt verder niet uit voor de functionaliteit, maar maakt het makkelijker debuggen later (extensie is in de praktijk altijd bla voor een datamodel,

2023-11-30 10:42 UTC, sophof commented on tests/testthat/test_write_fwf_blaise.R
> +  # Check the type/width of the fields, defined on lines 3 to 5 of the model.
Dit deel van de test kan denk ik beter als een aparte test en dan onder het lezen van een datamodel (`test_blaise_datamodel`)

2023-12-04 14:38 UTC, reijeridema commented on tests/testthat/test_write_fwf_blaise.R
> +  blafile = tempfile(fileext = '.asc')
Omdat het model nu apart getest wordt is deze regel geheel verdwenen.

2023-12-04 14:39 UTC, reijeridema commented on tests/testthat/test_write_fwf_blaise.R
> +  # Check the type/width of the fields, defined on lines 3 to 5 of the model.
Wat we eigenlijk willen testen is dat `get_model()` de juiste widths geeft. Dat lijkt niet op andere tests in `test_blaise_datamodel`, maar wel een beetje op tests in `test_write_datamodel`. Ik heb daar een test toegevoegd conform de andere tests in dat bestand.

2023-12-08 09:46 UTC, merged